### ISSUE TITLE
Text archeology

### ISSUE THREAD

**Issue by aptoptout** [davidpb90/Visualizing-Books#27]
How can we rebuild the book text with the spaces where they should be, the punctuation correct and chapters separated?

Probably using regular expressions.

**Comment by davidpb90** [comment]
I'll work on this one, probably it should be my main focus point. The best way I can think of is to store all the info in the tables. I would transform the text into a table indexing every single element, then send it through the current pipeline preserving indexes so that at the end we can join the derived new elements to the original table. I'll start with a draft this week.

**Comment by aptoptout** [comment]
awesome!
